### ISSUE TITLE
[Addition]: The Dark Side Hangar

### ISSUE THREAD

**Issue by CopperTFox** [cyberkitsune/chatbox-club-blacklist#12]
### World ID

wrld_e63fa5e2-f58d-4091-922c-c0c77227846d

### World Name

The Dark Side Hangar

### World URL

https://vrchat.com/home/world/wrld_e63fa5e2-f58d-4091-922c-c0c77227846d

### Comments

Hi,

Not the creator but Co-Owner of the Club.
If you're not 100% sure, DM me on Discord @CopperTFox and I'll verify to you that I am part of the Team.

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)

**Comment by CopperTFox** [comment]
Also, can I add another world directly here or do I need to open another Issue?

**Comment by cyberkitsune** [comment]
If you're just adding a handful it'd be good if you could open a second issue, helps keep me organized when adding these!
