### ISSUE TITLE
[Addition]: VRDancing

### ISSUE THREAD

**Issue by MixieVR** [cyberkitsune/chatbox-club-blacklist#18]
### World ID

wrld_42377cf1-c54f-45ed-8996-5875b0573a83

### World Name

VRDancing

### World URL

https://vrchat.com/home/world/wrld_42377cf1-c54f-45ed-8996-5875b0573a83

### Comments

VRDancing is not a club, but we are dancing to music and trying to maintain a clean line of sight for choreo videos and streams. We've had several annoyances with people using chatbox tools and people making a fuss when being asked to turn them off.

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Looks like you're the world creator so I'm happy to add this to the list even though it's not club specific! If you ever need it removed later on feel free to open another issue!

**Comment by MixieVR** [comment]
Thankyouuuuu! Much appreciated :)
