### ISSUE TITLE
[Addition]: The Station （Channel 1)

### ISSUE THREAD

**Issue by Apow08** [cyberkitsune/chatbox-club-blacklist#21]
### World ID

wrld_663ef684-edaa-4965-991f-4ac7cd93bc6b

### World Name

The Station （Channel 1)

### World URL

https://vrchat.com/home/world/wrld_663ef684-edaa-4965-991f-4ac7cd93bc6b

### Comments

First VRC World of The Station

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Thank you for requesting! I've added this world and all the others you've requested to the list :)
