### ISSUE TITLE
[Addition]: Nuzzle Inc․

### ISSUE THREAD

**Issue by Jazzy7498** [cyberkitsune/chatbox-club-blacklist#28]
### World ID

wrld_1ecdb265-8b8e-4ee9-8f1e-15fb13a9bc8b

### World Name

Nuzzle Inc

### World URL

https://vrchat.com/home/world/wrld_1ecdb265-8b8e-4ee9-8f1e-15fb13a9bc8b

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Added! Sorry for the delay.
