### ISSUE TITLE
[Addition]: Placeholder Club

### ISSUE THREAD

**Issue by TekCastPork** [cyberkitsune/chatbox-club-blacklist#3]
### World ID

wrld_0f67ce66-2622-4f6d-a623-6a8c4618bc45

### World Name

Placeholder Club

### World URL

https://vrchat.com/home/world/wrld_0f67ce66-2622-4f6d-a623-6a8c4618bc45

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)

**Comment by cyberkitsune** [comment]
Added in https://github.com/cyberkitsune/chatbox-club-blacklist/commit/0844409354953d741ba81b21512f38b6946fdb16

Thanks for requesting ^^
