### ISSUE TITLE
[Addition]: SANCTUM

### ISSUE THREAD

**Issue by MixieVR** [cyberkitsune/chatbox-club-blacklist#31]
### World ID

wrld_2095ba41-f0b8-4ed3-a00d-3f0e9a4e2a79

### World Name

SANCTUM

### World URL

https://vrchat.com/home/world/wrld_2095ba41-f0b8-4ed3-a00d-3f0e9a4e2a79

### Comments

The world is not uploaded under my account but I am part of the Sanctum development team.

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Added! Sorry for the delay.
