### ISSUE TITLE
[Addition]: BASS STATION

### ISSUE THREAD

**Issue by v-ai-rus** [cyberkitsune/chatbox-club-blacklist#33]
### World ID

wrld_1c82cdb4-cb19-4304-a23e-20cc6e0e6f8c

### World Name

Bass Station 2.0

### World URL

https://vrchat.com/home/world/wrld_1c82cdb4-cb19-4304-a23e-20cc6e0e6f8c

### Comments

I am not the world creator, Aves Protocol is the world creator, but I am the owner of the club in question.

Bass Station primarily is a music event oriented world.

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Added, ty for requesting!
