### ISSUE TITLE
[Addition]: Just Dance VRChat

### ISSUE THREAD

**Issue by SolarCatto** [cyberkitsune/chatbox-club-blacklist#35]
### World ID

wrld_f059e174-249c-4aa9-b1f2-3873ed9dfd89

### World Name

Just Dance VRChat

### World URL

https://vrchat.com/home/world/wrld_f059e174-249c-4aa9-b1f2-3873ed9dfd89

### Comments

I am _**not**_ the owner of the world, however the world is heavily based on being able to view a video screen to dance along with, which can be very easily occluded with a large chatbox player.

It is also music based (obviously, being a dancing world), so I believe it should be listed.

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
I'll list it for now but if there's complaints from users or the word creator this may be rolled back!
