### ISSUE TITLE
[Addition]: FURAVE

### ISSUE THREAD

**Issue by AlaskyMix** [cyberkitsune/chatbox-club-blacklist#36]
### World ID

wrld_baf8884a-6d9c-4f0e-bfa4-40eea314e7f3

### World Name

FURAVE

### World URL

https://vrchat.com/home/world/wrld_baf8884a-6d9c-4f0e-bfa4-40eea314e7f3

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Added, thanks for requesting!
