### ISSUE TITLE
[Addition]: _REALITY

### ISSUE THREAD

**Issue by dtupper** [cyberkitsune/chatbox-club-blacklist#38]
### World ID

wrld_5e8adb56-e91f-4e92-93e4-df04a5398395

### World Name

_REALITY

### World URL

https://vrchat.com/home/world/wrld_5e8adb56-e91f-4e92-93e4-df04a5398395

### Comments

Adding to list on behalf of Shelter team. I am not a staff member.

I believe _REALITY fulfills the guideline of "Worlds where broadcasting a player's current playing media is generally frowned upon".

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Thank you for requesting! `wrld_5e8adb56-e91f-4e92-93e4-df04a5398395` was added in the initial set of clubs in commit 0844409 -- Feel free to reopen this if the world ID changed! (I've also gone ahead and added the world you requested in #39)
