### ISSUE TITLE
[Addition]: _outlook

### ISSUE THREAD

**Issue by dtupper** [cyberkitsune/chatbox-club-blacklist#39]
### World ID

wrld_3736c10a-36ce-4dc6-bd42-5bc4085f0b45

### World Name

_outlook

### World URL

https://vrchat.com/home/world/wrld_3736c10a-36ce-4dc6-bd42-5bc4085f0b45

### Comments

Adding to list on behalf of Shelter team. I am not a staff member.

Please note that this world is not public. I retrieved the ID from my archived logs.

I believe _outlook fulfills the guideline of "Worlds where broadcasting a player's current playing media is generally frowned upon".

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Added! Thank you for requesting :)
