### ISSUE TITLE
[Addition]: Club Deviate

### ISSUE THREAD

**Issue by totcvrc** [cyberkitsune/chatbox-club-blacklist#44]
### World ID

wrld_95883f50-4838-4cea-9e80-3347c5caaf5e

### World Name

Club Deviate

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Added! Thanks for requesting
