### ISSUE TITLE
[Addition]: Rizumu Enclosure

### ISSUE THREAD

**Issue by Real-Aliquem** [cyberkitsune/chatbox-club-blacklist#45]
### World ID

wrld_af6e457d-06d7-42e4-86bc-19155024266c

### World Name

Rizumu Enclosure

### World URL

https://vrchat.com/home/world/wrld_af6e457d-06d7-42e4-86bc-19155024266c

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Added! Thanks for requesting

**Comment by Real-Aliquem** [comment]
Thank you kindly for adding both venues. Appreciate you <3
