### ISSUE TITLE
[Addition]: Neon Skyline Rizumu Edition

### ISSUE THREAD

**Issue by Real-Aliquem** [cyberkitsune/chatbox-club-blacklist#46]
### World ID

wrld_aba9a74f-6c7a-4e6f-bf38-b07e95835407

### World Name

Neon Skyline Rizumu Edition

### World URL

https://vrchat.com/home/world/wrld_aba9a74f-6c7a-4e6f-bf38-b07e95835407

### Addition guidelines

- [X] The world I am requesting meets the [guidelines.](https://github.com/cyberkitsune/chatbox-club-blacklist?tab=readme-ov-file#guidelines-for-addition--removal)
- [X] The world I am requesting is not already on the [current blacklist.](https://github.com/cyberkitsune/chatbox-club-blacklist/blob/master/npblacklist.json)

**Comment by cyberkitsune** [comment]
Added, thanks for requesting!
