### ISSUE TITLE
Private Worlds

### ISSUE THREAD

**Issue by Kreyadian** [cyberkitsune/chatbox-club-blacklist#5]
Just want to make sure before I add a few other worlds to the list but will this still work for private worlds such as [this one](https://vrchat.com/home/world/wrld_62b72c11-b85a-476a-80f0-edf5aa4c4088)?

**Comment by vesturo** [comment]
Yep, should still work ~ i'm pretty sure it checks the current VRC instance world id and checking against the list

**Comment by cyberkitsune** [comment]
Yup! Private worlds still work, just need the World ID and Name.
